UnixPB: Add Ubuntu 2104 to DockerStatic role
adoptium/infrastructure pull request #2189
Opened 2021-05-17 13:11 UTC by Haroon-Khel

ref #2143

2021-05-17 14:26 UTC, sxa reviewed
The [original PR](https://github.com/adoptium/infrastructure/pull/2188) said `Will test on a machine shortly` - have you done that now?

2021-05-17 14:54 UTC, Haroon-Khel commented
Changes run fine. Ubuntu 2104 docker image builds fine too. 

Based on what was already in the DockerStatic role, I used the port map 2226:22 for the ubuntu 2104 image. Testing on dockerhost-equinix-ubuntu2004-x64-1, (https://ci.adoptopenjdk.net/computer/test-docker-ubuntu2004-x64-1/), that port was already in use by a centos 8 docker container so I used a different port for testing. 

My question is should I keep it as 2226 in the playbooks?

2021-05-17 15:01 UTC, sxa commented
> My question is should I keep it as 2226 in the playbooks?

Honestly, since it's not an LTS release I'd either select a new one later down the list, or replace the port defined for 20.10 with this one and remove 20.10 from the role.

2021-05-17 15:49 UTC, Haroon-Khel commented
>Honestly, since it's not an LTS release I'd either select a new one later down the list, or replace the port defined for 20.10 with this one and remove 20.10 from the role.

Im in favour of the latter

2021-05-17 16:46 UTC, sxa requested changes
Let's ensure the machine name is consistent with the port number

2021-05-17 16:46 UTC, sxa commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/tasks/main.yml
> +  command: docker run --restart unless-stopped -p 2225:22 --cpus=4.0 --memory=6G --detach --name U2104_2226 aqa_u2104
```suggestion
  command: docker run --restart unless-stopped -p 2225:22 --cpus=4.0 --memory=6G --detach --name U2104_2225 aqa_u2104
```

2021-05-17 21:41 UTC, Haroon-Khel commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/tasks/main.yml
> +  command: docker run --restart unless-stopped -p 2225:22 --cpus=4.0 --memory=6G --detach --name U2104_2226 aqa_u2104
Ah I knew there was something I missed

2021-05-18 07:51 UTC, Willsparker approved these changes
LGTM :+1:

2021-05-22 12:34 UTC, sxa approved these changes
LGTM - Thanks!

2021-05-24 13:50 UTC, merged