QEMU: Change any occurrence of openjdk-tests to aqa-tests in the test script
adoptium/infrastructure pull request #2230
Opened 2021-06-22 10:43 UTC by Haroon-Khel

ref https://github.com/adoptium/infrastructure/issues/2121

The latest failure on the QEMU ppc64le job produces this failure

```
00:17:27 TESTDIR: /home/linux/testLocation/openjdk-tests is invalid. Please use --testdir|-t to set valid TESTDIR under aqa-tests. Default value current dir (pwd) is used if not provided.
00:17:32 /home/linux/openjdk-infrastructure/ansible/pbTestScripts/testJDK.sh: line 15: cd: /home/linux/testLocation/openjdk-tests/TKG: No such file or directory
00:17:32 + grep -q 'FAILED: 0' /home/vagrant1/workspace/QEMUPlaybookCheck/ARCHITECTURE/ppc64le/OS/ubuntu18/label/vagrant/ansible/pbTestScripts/qemu_pbCheck/logFiles/UBUNTU18.PPC64LE.test_log
00:17:32 + echo TEST FAILED
```

The other QEMU jobs would produce the same failure if they get to the test stage, but they keep failing before that.

Making these changes fixes the issue on my local machine, will test on the QEMU disk image before merging

2021-06-22 13:08 UTC, sxa requested changes
This PR seems to be missing the template - can you add it back in and ensure that the appropriate prefix is on the commit (`pbTests:`) and that a link is provided to VPC/QPC runs to verify this change.

2021-06-22 18:12 UTC, Haroon-Khel commented
Ive temporarily changed the config of the QEMU job to pick up this pr. Running the full playbook, build and test on ppc64le, as seems to be the only one that can make it to the test stage, at https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/276/

2021-06-22 21:13 UTC, gdams approved these changes

2021-06-23 11:07 UTC, Haroon-Khel commented
Annoyingly https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/ARCHITECTURE=ppc64le,OS=ubuntu18,label=vagrant/276/console failed with the same error as if the changes were not implemented. I have certainly changed the config of the QEMU job to pick up from the branch of this pr

2021-06-23 11:20 UTC, Haroon-Khel commented
Running another job at https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/277/console
It should retrieve the infrastructure repo from my branch this time

2021-06-23 16:38 UTC, sxa approved these changes

2021-06-23 16:39 UTC, sxa commented
Approved for when test runs pass :-)

2021-06-23 16:42 UTC, sxa commented
Re-running a VPC building HotSpot at https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1187 since the OpenJ9 codebase seems to have a build break just now.

2021-06-23 18:43 UTC, Haroon-Khel commented
>Re-running a VPC building HotSpot at https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1187 since the OpenJ9 codebase seems to have a build break just now.

That might explain why https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/277/console broke during the build step. I didn't notice it builds openj9 by default

2021-06-24 09:47 UTC, sxa commented
Apologies - I added that comment about the re-run into the wrong issue - my VPC run does NOT have the changes in this PR.

> I didn't notice it builds openj9 by default

Yes that's intentional because OpenJ9 has more prereqs so is generally a better test of whether the playbooks have worked.

2021-06-24 10:31 UTC, karianna commented
Needs rebasing to pick up linter fixes?

2021-06-24 16:12 UTC, sxa commented
I'll add my approval once https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/ARCHITECTURE=ppc64le,OS=ubuntu18,label=vagrant/278/console passes through this piece of the code ;-)

2021-06-25 13:29 UTC, Haroon-Khel commented
https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/ARCHITECTURE=ppc64le,OS=ubuntu18,label=vagrant/278/console passed. The test step did not hit the same error

>Needs rebasing to pick up linter fixes?

I could, but the linter errors and warnings do not concern changes made by this pr. Could it be merged anyway?

2021-06-25 14:20 UTC, merged