add skytap ppc64le linux machines
adoptium/infrastructure pull request #2238
Opened 2021-06-25 13:49 UTC by gdams

##### Checklist

- [ ] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

2021-06-25 13:55 UTC, sxa requested changes
First checked item in the list is fake news - can you add an `inventory:` prefix to the commit message please?

2021-06-25 13:56 UTC, gdams commented
> First checked item in the list is fake news - can you add an inventory: prefix to the commit message please?

@sxa it will be updated when we squash and merge right?

2021-06-26 09:47 UTC, gdams commented on ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Get_Vendor_Files/tasks/main.yml
> +  raw: dotgpg cat {{ item }}
I was getting issues with gem bundles not being in the PATH (it's to do with the way that Ansible spawns a command. Running it as `raw` fixed the issue.

2021-06-27 19:34 UTC, sxa approved these changes

2021-06-28 08:19 UTC, merged