pbTests: Add check to see if fork exists
adoptium/infrastructure pull request #2304
Opened 2021-09-02 17:14 UTC by Haroon-Khel

- [ ] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

ref https://github.com/adoptium/infrastructure/issues/2295

I've added a check to determine whether the fork is labelled either `openjdk-infrastructure` or `infrastructure`.

This code works when run separately, but not when I add it to the vagrantPlaybookCheck.sh script; the script seems to get caught on the curl commands. Hence I'm keeping this as a WIP for now

2021-09-07 16:28 UTC, Haroon-Khel commented
I've fixed this issue with the script regarding choosing the correct repo name, `openjdk-infrastructure` or `infrastructure`, as evidenced by https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1228/OS=Ubuntu2004,label=vagrant/console. The script runs fine in a terminal environment when run on the VPC machine, however the VPC jenkins job fails occasionally (despite finding the correct repo name) https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1227/OS=Ubuntu2004,label=vagrant/console

2021-09-07 16:50 UTC, Haroon-Khel commented
On a second inspection, it may just be my fork of the infra repo that the jenkins VPC job has a problem with.

https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1229/OS=Ubuntu2004,label=vagrant/console
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Ubuntu2004,label=vagrant/1231/console and
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1228/OS=Ubuntu2004,label=vagrant/console 

all make it passed the git clone stage, but 
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1230/OS=Ubuntu2004,label=vagrant/console fails at the git clone stage. In which case, this failure seems unrelated to this pr which I feel can be merged

2021-09-09 10:42 UTC, sxa requested changes
One quick change then we're good.

2021-09-09 10:42 UTC, sxa commented on ansible/pbTestScripts/buildJDK.sh
> +			echo "Fork not found"
```suggestion
			echo "Repository not found - must be a fork called temurin-build or openjdk-build"
```

2021-09-09 12:20 UTC, Haroon-Khel commented
Changes look good on https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Ubuntu2004,label=vagrant/1234/console which uses a `temurin-build` named fork

2021-09-14 11:19 UTC, sxa approved these changes

2021-09-14 16:34 UTC, merged