Docker: Add script to update docker containers
adoptium/infrastructure pull request #2406
Opened 2021-12-09 12:55 UTC by Haroon-Khel

- [ ] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

ref https://github.com/adoptium/infrastructure/issues/2070

Makes https://github.com/adoptium/infrastructure/pull/2398 redundant as I could not get cron jobs to work in the containers, so have decided to implement a cron job on the host

2021-12-10 11:52 UTC, karianna reviewed
Is this a wanted change?  Do we not need to pin our versions for reproducible builds?

2021-12-14 16:11 UTC, sxa commented
> Is this a wanted change? Do we not need to pin our versions for reproducible builds?

That can be a separate discussion but I do not want machines on the network that are unsupported or do not undergo security patching. This brings the static docker containers up to the same patching that we have for all our other machines as per the playbooks.

2021-12-14 16:14 UTC, sxa requested changes
One minor point, otherwise I believe this is good.

2021-12-14 16:14 UTC, sxa commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/scripts/updatepackages.sh
> +done
Should have a newline at the end

2021-12-16 11:56 UTC, Haroon-Khel commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/scripts/updatepackages.sh
> +done
Done

2021-12-16 12:22 UTC, sxa approved these changes

2021-12-17 15:19 UTC, merged