Docker: Enable ipv6 on in docker dockerhost machines
adoptium/infrastructure pull request #2520
Opened 2022-04-01 11:29 UTC by Haroon-Khel

- [ ] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

ref https://github.com/adoptium/infrastructure/issues/2517#issuecomment-1084815153

Ipv6 needs to be enabled for docker on our dockerhost machines in order for certain ipv6 net tests, in jdk_net, to pass on containers on these dockerhost machine

2022-04-01 12:06 UTC, Haroon-Khel commented
```
Error: yaml trailing spaces
Error: yaml trailing spaces
Error: fqcn-builtins Use FQCN for builtin actions.
Error: fqcn-builtins Use FQCN for builtin actions.
```
Annoyingly the error isn't showing me where the trailing spaces are

2022-04-04 22:24 UTC, sxa requested changes
A couple of points:
1. Has this been verified to solve the problem? I would suggest we take one of the two x64 dockerhost machines tomorrow and test that the extra option allows the tests to pass.
2. This is causing a restart regardless of whether the configuration has been changed. I suggest we modify this to only make the change if the extra line has been added, otherwise whenever we run the playbooks to update a machine it's going to restart the docker service which will likely cause problems for any jobs running inside the existing ones.

2022-04-05 11:45 UTC, Haroon-Khel commented
> Has this been verified to solve the problem? I would suggest we take one of the two x64 dockerhost machines tomorrow and test that the extra option allows the tests to pass.

In the linked issue, https://ci.adoptopenjdk.net/job/Grinder/4194/console ran on test-docker-alpine314-x64-2 (hosted on docker-packet-ubuntu2004-intel-1) showed ipv6 test failures [here](https://github.com/adoptium/infrastructure/issues/2517#issuecomment-1084480131). Adding the fix to docker-packet-ubuntu2004-intel-1 seemed to allow the tests to pass, https://ci.adoptopenjdk.net/job/Grinder/4234/console

I've kicked off a jdk_net test job on test-docker-alpine311-x64-1 which is hosted on docker-packet-ubuntu2004-amd-1. 
https://ci.adoptopenjdk.net/job/Grinder/4306/console

2022-04-05 12:24 UTC, sxa approved these changes
LGTM now subject to any real issues with the checks being resolved.

2022-04-05 15:01 UTC, Haroon-Khel commented
https://ci.adoptopenjdk.net/job/Grinder/4306/console on docker-packet-ubuntu2004-amd-1 failed, but after adding the fixed, it has passed https://ci.adoptopenjdk.net/job/Grinder/4307/console

2022-04-05 15:01 UTC, merged