[WIP] docker: add support for Alpine aarch64 image #2497
adoptium/infrastructure pull request #2535
Opened 2022-04-19 10:38 UTC by zdtsw

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [x] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

Ref: https://github.com/adoptium/infrastructure/issues/2497

2022-04-20 05:29 UTC, zdtsw commented
several parts in this PR I am not 100% sure:
- skip [test_tools ](https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Alpine.yml#L46) which I do not think should be included in the final docker image release to end-user
- keep[build_tools](https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Alpine.yml#L7) but I am not sure if all these tools are needed. To only make ansible work, unzip tar should be enough
- other dockerfile (i.e for centos7) handle jenkins [user and group](https://github.com/adoptium/infrastructure/blob/master/ansible/docker/Dockerfile.CentOS7#L18) which I do not think is needed, that's why I did not add for alpine dockerfile. Should we cleanup this part later (in another PR)?

2022-04-20 11:16 UTC, sxa commented
Please leave `test_tools` in for consistency with the other platforms in case we want to run some basic smoke tests inside the container.

2022-04-20 11:17 UTC, sxa commented
I'm not quite sure why the username is handled differently, but for now I'm happy with leaving it the same as it does for Alpine/x64, and if we decide to change we can discuss more widely.

2022-05-10 09:57 UTC, sxa requested changes
One minor comment change, then I'm ok to approve and merge this :-D

2022-05-10 09:57 UTC, sxa commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Alpine.yml
> +- name: Install JDK for aarch64
```suggestion
- name: Install JDK for x64
```

2022-05-10 10:44 UTC, sxa approved these changes
Thanks - will merge once checks complete. We can probably prepare a PR in https://github.com/adoptium/ci-jenkins-pipelines to utilise this now - there are a few examples of adding extra builds in if you look at the PR history in that repository :-)

2022-05-10 10:51 UTC, zdtsw commented
> Thanks - will merge once checks complete. We can probably prepare a PR in https://github.com/adoptium/ci-jenkins-pipelines to utilise this now - there are a few examples of adding extra builds in if you look at the PR history in that repository :-)

thanks, will do!

2022-05-10 11:20 UTC, zdtsw commented
> Thanks - will merge once checks complete. We can probably prepare a PR in https://github.com/adoptium/ci-jenkins-pipelines to utilise this now - there are a few examples of adding extra builds in if you look at the PR history in that repository :-)

Sorry, but I thought https://ci.adoptopenjdk.net/job/centos7_docker_image_updater/ is triggered by any changes into "infrastructure" repo's default branch and load Jenkinsfile itself. 
anything  more in "ci-jenkins-pipeline" repo to enable build new docker image?

2022-05-10 11:25 UTC, sxa commented
> > Thanks - will merge once checks complete. We can probably prepare a PR in https://github.com/adoptium/ci-jenkins-pipelines to utilise this now - there are a few examples of adding extra builds in if you look at the PR history in that repository :-)
> 
> Sorry, but I thought https://ci.adoptopenjdk.net/job/centos7_docker_image_updater/ is triggered by any changes into "infrastructure" repo's default branch and load Jenkinsfile itself. anything more in "ci-jenkins-pipeline" repo to enable build new docker image?

Yep that's correct - this PR should trigger the creation of the docker image, but we also need to tell jenkins to include Alpine/aarch64 bulids when it runs the regular pipelines, so we need to add it into the files in https://github.com/adoptium/ci-jenkins-pipelines/tree/master/pipelines/jobs/configurations for java to be built using those docker images.

2022-05-10 11:26 UTC, merged