UnixPb: Add arm64 binaries on MacOS instead of x64 when available
adoptium/infrastructure pull request #2572
Opened 2022-05-23 11:18 UTC by Haroon-Khel

- [ ] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

2022-05-23 16:24 UTC, karianna requested changes
One small change

2022-05-23 16:24 UTC, karianna commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml
> +    - jdk_version == 11 or jdk_version == 17 or jdk_version == 18
IS this really going to be 17+ going forwards?

2022-05-24 11:06 UTC, Haroon-Khel commented
Fixes https://github.com/adoptium/infrastructure/issues/2518

2022-05-24 13:07 UTC, karianna approved these changes
LGTM

2022-05-24 13:35 UTC, sxa approved these changes

2022-05-24 22:39 UTC, merged