Testing faq
adoptium/infrastructure pull request #2574
Opened 2022-05-24 13:48 UTC by sxa

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [x] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

Update examples to be a table rather than a bulleted list and add the UBI8 `sleep` test case.
Dratft until I figure out how to run `_MachineInfo` properly in a grinder ...

2022-05-30 18:59 UTC, smlambert approved these changes

2022-05-31 11:29 UTC, Haroon-Khel requested changes

2022-05-31 11:29 UTC, Haroon-Khel commented on FAQ.md
> +make compiler
```suggestion
make compile
```
A little typo (https://github.com/eclipse-openj9/openj9/wiki/Reproducing-Test-Failures-Locally#general-steps)

2022-05-31 12:09 UTC, sxa commented on FAQ.md
> +make compiler
Well spotted @Haroon-Khel !

2022-06-01 11:58 UTC, Haroon-Khel approved these changes
LGTM

2022-06-01 11:58 UTC, merged