docker: Add Dockerstatic File for Debian 11.
adoptium/infrastructure pull request #2649
Opened 2022-06-28 10:07 UTC by steelhead31

##### Checklist

- [X] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [X] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [X] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

2022-06-28 10:36 UTC, steelhead31 commented
JDK copied to docker container, and quick aqa test run against JDK8  
  
TEST TARGETS SUMMARY  
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  
PASSED test targets:  
MBCS\_Tests\_pref\_ja\_JP\_linux\_0

TOTAL: 1   EXECUTED: 1   PASSED: 1   FAILED: 0   DISABLED: 0   SKIPPED: 0  
ALL TESTS PASSED  
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

\_MBCS\_Tests\_pref\_ja\_JP\_linux\_0 done

2022-06-28 10:59 UTC, karianna requested changes

2022-06-28 10:59 UTC, karianna commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.deb11
> +RUN wget -q 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk8?openjdk_impl=hotspot&os=linux&arch=x64&release=latest&type=jdk' -O /tmp/jdk8.tar.gz
Would be good to fix others if this was a C&P

2022-06-28 11:22 UTC, Haroon-Khel reviewed
Aside from Martijn's changes, it looks good. I'll get a deb11 container running off these changes and then approve

2022-06-28 12:35 UTC, steelhead31 commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.deb11
> +RUN wget -q 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk8?openjdk_impl=hotspot&os=linux&arch=x64&release=latest&type=jdk' -O /tmp/jdk8.tar.gz
Fixed this, was a C&P error on my part, the other dockerstatic files have been updated in a previous PR.

2022-06-28 12:35 UTC, steelhead31 commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.deb11
> +RUN wget -q -O /tmp/ant.zip 'https://archive.apache.org/dist/ant/binaries/apache-ant-1.10.5-bin.zip'
Ant & Ant Contrib updated to latest versions.

2022-06-28 13:15 UTC, karianna approved these changes
LGTM

2022-06-28 13:54 UTC, steelhead31 commented
> Aside from Martijn's changes, it looks good. I'll get a deb11 container running off these changes and then approve

@Haroon-Khel all good now, thanks!

2022-06-28 16:20 UTC, Haroon-Khel approved these changes
Got the container up and running at https://ci.adoptopenjdk.net/computer/test-docker-debian11-x64-1/

2022-06-28 16:28 UTC, Haroon-Khel commented
@steelhead31 
While running a grinder on the container, at https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5048/console, it hit this error
```
17:21:54  Buildfile: /home/jenkins/workspace/Grinder/aqa-tests/TKG/scripts/build_test.xml
17:21:55    [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.
17:21:55    [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.
```
You think it could be related to the updated versions of Ant & Ant Contrib?

2022-06-28 16:29 UTC, Haroon-Khel requested changes
@steelhead31 
While running a grinder on the container, at https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5048/console, it hit this error
```
17:21:54  Buildfile: /home/jenkins/workspace/Grinder/aqa-tests/TKG/scripts/build_test.xml
17:21:55    [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.
17:21:55    [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.
```
You think it could be related to the updated versions of Ant & Ant Contrib?

2022-06-29 07:15 UTC, steelhead31 commented
> @steelhead31 While running a grinder on the container, at https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5048/console, it hit this error
> 
> ```
> 17:21:54  Buildfile: /home/jenkins/workspace/Grinder/aqa-tests/TKG/scripts/build_test.xml
> 17:21:55    [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.
> 17:21:55    [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.
> ```
> 
> You think it could be related to the updated versions of Ant & Ant Contrib?

Yup, almost certainly is.. I'll do some investigation and try downgrading ant-contrib as I think thats likely the source of the problem.

2022-06-29 07:42 UTC, steelhead31 commented
@Haroon-Khel would you mind re-spinning the docker and running another test, it seems much happier with the old version of ant-contrib. I'll log a separate issue to investigate what will be required to upgrade to the new ant-contrib.

2022-06-29 11:35 UTC, Haroon-Khel commented
New grinder running on the rebuilt image/container https://ci.adoptopenjdk.net/job/Grinder/5055/console

2022-06-29 20:41 UTC, Haroon-Khel approved these changes
Grinder passed. LGTM

2022-06-30 08:45 UTC, merged