Add AIX 7.2 build machine to the inventory file
adoptium/infrastructure pull request #2655
Opened 2022-06-30 15:16 UTC by sxa

Only one of them, but in a push the test machine (which we were using for building JDK19+ for a while) can be used too as a backup system.

##### Checklist

- [ ] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [x] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [x] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [x] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly (Not bastillion yet but will complete next week)

2022-06-30 17:30 UTC, karianna requested changes

2022-06-30 17:30 UTC, karianna commented on ansible/inventory.yml
> +r
```suggestion
```

2022-07-01 06:52 UTC, sxa commented
Rebased to remove extra stuff that was in this PR.

2022-07-01 10:20 UTC, karianna approved these changes

2022-07-01 10:21 UTC, merged