Dockerstatic: Install shared-mime-info on fedora docker static containers
adoptium/infrastructure pull request #2679
Opened 2022-07-19 15:48 UTC by Haroon-Khel

- [ ] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

ref https://github.com/adoptium/infrastructure/issues/2631#issuecomment-1188992683

The test jdk8 java/nio/file/Files/probeContentType/Basic.java seems to pass on fedora only when this package is installed

Tested on test-docker-fedora36-x64-1

Before install
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5225/

After install
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5226/

2022-08-01 10:09 UTC, sxa requested changes
Can you add a prefix onto the commit messge please as per the PR template checklist

2022-08-01 10:21 UTC, karianna approved these changes
LGTM

2022-08-10 11:18 UTC, sxa requested changes
@Haroon-Khel You've changed the PR title but not the commit message which is the important bit since that shows in the commit history in the repository.

2022-08-10 13:07 UTC, Haroon-Khel commented
Changed the commit message, but my git cli wouldn't push without making an unnecessary merge

2022-08-11 07:34 UTC, sxa approved these changes
Yeah a force push is the way to do it. I'll do the squash & merge on this one and try to ensure the "correct" commit message is included sine I'm not sure it will be by defualt

2022-08-11 09:45 UTC, merged