Docker: Add Ansible support for docker on Rhel8
adoptium/infrastructure pull request #2721
Opened 2022-08-30 15:49 UTC by Haroon-Khel

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [x] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

ref https://github.com/adoptium/infrastructure/issues/2710

Added support for docker to be installed on rhel8 (ppc64, x64 and s390x)
Old ppc64le and x64 repo url no longer valid. Updated them to use a centos docker repo
The docker repo key is the same for rhel and centos

2022-08-30 15:51 UTC, Haroon-Khel commented
Centos 6 7 and 8 vpc checks https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1526/console

2022-08-30 16:05 UTC, zdtsw approved these changes

2022-08-30 16:06 UTC, zdtsw commented
just one more thing, why we set `gpgcheck: false` ?

2022-08-30 18:15 UTC, karianna commented
Linter is not happy

2022-09-05 14:54 UTC, sxa commented
> Linter is not happy

ping @Haroon-Khel

2022-09-05 15:51 UTC, sxa requested changes
Unless there's a good reason not to, let's change this conditional to make it easier to deploy on new OS versions in the future.

2022-09-05 15:51 UTC, sxa commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml
> +        - ansible_distribution_major_version == "7" or ansible_distribution_major_version == "8"
Can I suggest we make this !=6 or >=7 so we have future compatibility?

2022-09-08 11:12 UTC, Haroon-Khel commented
ping @sxa for rereview

2022-10-03 14:05 UTC, sxa commented
New VPC with latest version at https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1553/

2022-10-04 12:57 UTC, sxa approved these changes
> New VPC with latest version at https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1553/

LGTM

2022-10-04 13:01 UTC, merged