Adding a check for the machines with the build, windows & x64 labels
adoptium/infrastructure pull request #2798
Opened 2022-10-20 09:36 UTC by lumuchris256

Added a check for the machines with the build, windows & x64 labels  
 updated the readme.md file in the ansible/playbooks/nagios/README.md with a new section detailing how to add an additional version of these checks.
fixes #2765 

cc @steelhead31 @smlambert @sxa

2022-10-20 09:38 UTC, karianna requested changes

2022-10-20 09:38 UTC, karianna commented on ansible/playbooks/nagios/README.md
> +        host_name                       Nagios_Server
Not sure the indenting is right here.

2022-10-20 09:38 UTC, karianna commented on ansible/playbooks/nagios/README.md
> +
extra whitespace

2022-10-20 09:57 UTC, lumuchris256 commented on ansible/playbooks/nagios/README.md
> +
committed the requested changes

2022-10-20 10:10 UTC, lumuchris256 commented on ansible/playbooks/nagios/README.md
> +        host_name                       Nagios_Server
corrected

2022-10-20 15:31 UTC, gdams commented on ansible/playbooks/nagios/README.md
> +## How to Add Additional Jenkins Check Label Job To Nagios Server Group For windows ##
```suggestion
## How to add additional Jenkins Check Label Job To Nagios server group For Windows ##
```

2022-10-20 15:32 UTC, gdams commented
1 nit but LGTM other than that

2022-10-21 12:41 UTC, lumuchris256 commented
> 1 nit but LGTM other than that

worked on

2022-10-25 11:39 UTC, steelhead31 requested changes
Some changes required....  as this is an instance of a new check, this section isnt needed

2022-10-25 11:39 UTC, steelhead31 commented on ansible/playbooks/nagios/README.md
> +```
This section isnt required, as check\_label already exists as a command, we dont need to create a duplicate

2022-10-25 11:39 UTC, steelhead31 commented on ansible/playbooks/nagios/README.md
> +*  Amend the machine specific config file, e.g ( /usr/local/nagios/etc/objects/localhost.cfg ) to include the entry for the new label check.
Amend the machine specific config file is not relevant for adding a check run by the nagios server itself, the only file to be changed is local host,  Id change the words "machine specific" for "nagios server"

2022-11-11 14:05 UTC, steelhead31 approved these changes
LGTM, I've used this to add the check for windows hosts, which can be seen in production nagios server now.

2022-11-11 14:05 UTC, steelhead31 commented
/thaw

2022-11-23 12:34 UTC, sxa commented
@karianna Are you ok with this one now?

2022-11-24 21:24 UTC, karianna approved these changes
LGTM

2022-11-24 21:24 UTC, merged