Create a Script To add Nagios Host Groups
adoptium/infrastructure pull request #2801
Opened 2022-10-21 07:26 UTC by julian55455

Fixes part of https://github.com/adoptium/infrastructure/issues/2788

2022-10-21 09:21 UTC, gdams reviewed
Not sure how I feel about the filename here... I'd much prefer `nagios_host_group_add.sh`

2022-10-21 12:10 UTC, julian55455 commented
@gdams sorry I clicked the review button twice. But I changed the file name

2022-10-21 12:37 UTC, karianna requested changes
Made suggested edits

2022-10-21 12:37 UTC, karianna commented on ansible/playbooks/nagios/roles/Nagios_Server/scripts/nagios_host_group_add.sh
> +echo "enter the hostgroup elias"
```suggestion
echo "enter the hostgroup alias"
```

2022-10-21 12:37 UTC, karianna commented on ansible/playbooks/nagios/roles/Nagios_Server/scripts/nagios_host_group_add.sh
> +read hostgroup_elias
```suggestion
read hostgroup_alias
```

2022-10-21 12:37 UTC, karianna commented on ansible/playbooks/nagios/roles/Nagios_Server/scripts/nagios_host_group_add.sh
> +echo "        alias           $hostgroup_elias" >> /usr/local/nagios/etc/objects/hostgroups.cfg
```suggestion
echo "        alias           $hostgroup_alias" >> /usr/local/nagios/etc/objects/hostgroups.cfg
```

2022-10-21 12:37 UTC, karianna approved these changes

2022-11-15 08:58 UTC, steelhead31 approved these changes
LGTM

2022-11-15 08:58 UTC, steelhead31 commented
/thaw

2022-11-15 09:17 UTC, gdams commented
/thaw

2022-11-15 09:28 UTC, merged