[ansible] Install docker for Ubuntu on RISC-V
adoptium/infrastructure pull request #2850
Opened 2022-12-12 14:48 UTC by luhenry

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

2022-12-14 01:24 UTC, karianna requested changes
Probably need to fix that TODO for security/stability reasons.

2022-12-14 01:24 UTC, karianna commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml
> +        state: latest   # TODO: Package installs should not use latest
```suggestion
        state: latest  # TODO: Package installs should not use latest
```

2022-12-21 09:32 UTC, gdams approved these changes

2022-12-28 08:00 UTC, karianna approved these changes
LGTM

2023-02-06 12:29 UTC, sxa requested changes
Can we add a version check in here since I don't think all versions of Ubuntu on RISC-V have the `docker.io` package available.

2023-11-11 09:38 UTC, closed without merging