Amend Nagios/Ansible Config Role To Create Service Groups Config File
adoptium/infrastructure pull request #2898
Opened 2023-01-30 10:18 UTC by lumuchris256

Updated the Nagios_Config playbook to create the Hostgroups.cfg file that contains a service group entry for each of the group types in the inventory

Fixes #2864 
signed off by @lumuchris256 
cc @steelhead31 @Haroon-Khel @smlambert

2023-01-31 12:17 UTC, steelhead31 commented
This PR will require changes, on a clean run of the playbooks..I get this error..  
  
TASK \[Nagios\_Config : Run Create Nagios Hostgroups script\] \*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*  
fatal: \[localhost\]: FAILED! => {"changed": true, "msg": "non-zero return code", "rc": 1, "stderr": "Traceback (most recent call last):\\n  File \\"/home/vagrant/.ansible/tmp/ansible-tmp-1675167368.6075487-39101-189259814438941/Create\_Nagios\_Hostgroups.py\\", line 20, in \<module>\\n    Nagios\_Service\_Types = sys.argv\[3\]\\nIndexError: list index out of range\\n", "stderr\_lines": \["Traceback (most recent call last):", "  File \\"/home/vagrant/.ansible/tmp/ansible-tmp-1675167368.6075487-39101-189259814438941/Create\_Nagios\_Hostgroups.py\\", line 20, in \<module>", "    Nagios\_Service\_Types = sys.argv\[3\]", "IndexError: list index out of range"\], "stdout": "", "stdout\_lines": \[\]}  
 

I'll do some investigation and try and find out what isnt working.

2023-01-31 12:29 UTC, steelhead31 requested changes

2023-01-31 12:29 UTC, steelhead31 commented on ansible/playbooks/nagios/roles/Nagios_Config/tasks/Create_Nagios_Hostgroups.yml
> +  script: ../scripts/Create_Nagios_Hostgroups.py "{{Nagios_Base_Path}}/etc/objects" "{{Nagios_Service_Types}}"
```suggestion
  script: ../scripts/Create_Nagios_Hostgroups.py "{{Input_Path}}" "{{Nagios_Base_Path}}/etc/objects" "{{Nagios_Service_Types}}"
```

2023-01-31 12:29 UTC, steelhead31 commented on ansible/playbooks/nagios/roles/Nagios_Config/tasks/Create_Nagios_Hostgroups.yml
> +  script: ../scripts/Create_Nagios_Hostgroups.py "{{Nagios_Base_Path}}/etc/objects" "{{Nagios_Service_Types}}"
Requires the path to the inventory to be added.

2023-01-31 12:29 UTC, steelhead31 commented on ansible/playbooks/nagios/roles/Nagios_Config/scripts/Create_Nagios_Hostgroups.py
> +    with open('hostgroups.cfg', 'w') as f:
```suggestion
    with open(f"{Output_Path}/hostgroups.cfg", "w") as f:
```

2023-01-31 12:29 UTC, steelhead31 commented on ansible/playbooks/nagios/roles/Nagios_Config/scripts/Create_Nagios_Hostgroups.py
> +    with open('hostgroups.cfg', 'w') as f:
Include the relative output pathing.

2023-02-06 12:54 UTC, sxa approved these changes
Looks reasonable overall, and I'll trust @steelhead31 to check that it works so I'm giving the second approval!

2023-02-06 13:12 UTC, merged