docs: add Scott Fryer as infrastructure team member
adoptium/infrastructure pull request #2901
Opened 2023-01-30 11:42 UTC by sxa

Fixes https://github.com/adoptium/infrastructure/issues/2749

Signed-off-by: Stewart X Addison <sxa@redhat.com>

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [x] other documentation is changed or added (if applicable)

2023-01-30 23:19 UTC, karianna requested changes

2023-01-30 23:19 UTC, karianna commented on README.md
> +* [@steelhead31](https://github.com/steelhead31) - Scorr Fryer (Red Hat)
```suggestion
* [@steelhead31](https://github.com/steelhead31) - Scott Fryer (Red Hat)
```

2023-01-31 11:34 UTC, steelhead31 approved these changes
LGTM

2023-01-31 19:31 UTC, karianna approved these changes

2023-01-31 19:31 UTC, merged