winPB: automate jenkins service installation
adoptium/infrastructure pull request #2994
Opened 2023-03-15 13:46 UTC by gdams

##### Checklist

- [ ] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

A few considerations here:

1. This role assumes that you want to the workdir to be `C:\Users\jenkins` (we could add overrides in the inventory.yml if needed)
2. This role assumes that `jenkins_secret` is set and contains the secret from Jenkins. I propose that we upload these secets to the vendor_files folder in the secrets repo and automatically set it based on the server name. Thoughts??

2023-03-17 01:21 UTC, karianna commented on ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Jenkins_Service_Installation/tasks/main.yml
> +    url: https://github.com/winsw/winsw/releases/download/v2.12.0/WinSW-x64.exe
Do we need to verify that download?

2023-03-17 01:21 UTC, karianna commented on ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Jenkins_Service_Installation/templates/JenkinsAgentService.xml.j2
> +	<executable>C:\openjdk\jdk-17\bin\java.exe</executable>
extract version?

2023-03-20 13:04 UTC, gdams commented on ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
> +      tags: [jenkins, adoptopenjdk]
we likely should but that would be a change to many existing roles. I'd suggest doing this in a separate PR

2023-03-20 13:12 UTC, gdams commented on ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Jenkins_Service_Installation/tasks/main.yml
> +    url: https://github.com/winsw/winsw/releases/download/v2.12.0/WinSW-x64.exe
yup

2023-03-20 13:45 UTC, sxa requested changes
Can we get a doc update along with this (e.g. to https://github.com/adoptium/infrastructure/tree/master/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/README.md) to cover the variable overrides that may be required (e.g. secret and workspace dir)

(Noting that such an update will conflict with https://github.com/adoptium/infrastructure/pull/2993/files but if it's a separate paragraph it'll be easy to merge :-) )

2023-03-21 07:06 UTC, karianna approved these changes

2023-04-12 11:52 UTC, gdams commented
> Can we get a doc update along with this (e.g. to

@sxa I've added some docs

2023-04-12 11:54 UTC, gdams commented
/thaw

2023-04-13 00:08 UTC, karianna commented
Playbook failures related?

2023-04-13 07:42 UTC, gdams commented
> Playbook failures related?

Unrelated

2023-04-13 09:01 UTC, sxa approved these changes
LGTM - thanks for the doc updates

2023-04-13 09:58 UTC, merged