Update installed JDKs to match current boot JDK requirements
adoptium/infrastructure pull request #3073
Opened 2023-05-24 11:57 UTC by sxa

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [x] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access): https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/

Draft pending VPC checks and verification that the build uses the installed JDK20 but approvals welcome in the meantime.

2023-05-24 15:04 UTC, sxa commented
This is going to require a bit more work because it's trying to pull JDK20 from api.adoptopenjdk.net which does redirect to adoptium, so I'm going to stick this in draft for now until it can be progressed.

2023-11-01 17:09 UTC, sxa commented
On hold until we come up with something sane to do for Linux on s390x and arm32

2024-02-16 23:55 UTC, karianna commented
@sxa Needs a rebase

2024-03-08 12:52 UTC, sxa commented
VPC: https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/1845/

2024-03-08 16:49 UTC, adamfarley requested changes
Most of it LGTM. 2 concerns:

- Various Yaml Lint and Ansible lint failures. The latter seem to be caused by the "---" being before the first comment block in a few files, as the error doesn't seem to pop up when the "---" is after the first comment block.
- Lines 190 and 223 in ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml look like a merge has gone wrong. Pls fix thnx. :)

2024-03-08 18:38 UTC, sxa commented
GPG signature verification is failing with this change so some extra remediation will be required for that.

2024-03-10 18:39 UTC, sxa commented
AIX and Linux (including riscv64 tested separately as it has different paths through the playbooks) are working properly now. Windows still undergoing testing...

2024-03-11 00:11 UTC, sxa commented
Windows now looking good: https://ci.adoptium.net/job/VagrantPlaybookCheck/1855/

2024-03-11 12:29 UTC, sxa commented
CentOS6 and Solaris also now clean (Both have special paths in this particular role at present.

2024-03-11 13:45 UTC, adamfarley commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml
> +# ansible install adopt binary  into /usr/lib/jvm/JDK_VERSION #
```suggestion
# ansible install adopt binary into /usr/lib/jvm/JDK_VERSION #
```

2024-03-11 13:46 UTC, adamfarley commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml
> +###############################################################
```suggestion
##############################################################
```

2024-03-11 13:47 UTC, adamfarley commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml
> +###############################################################
```suggestion
##############################################################
```

2024-03-11 13:47 UTC, adamfarley commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml
> +###############################################################
Lining up comment hashes.

2024-03-11 13:49 UTC, adamfarley approved these changes
LGTM

2024-03-11 13:50 UTC, adamfarley commented
And thanks for handling all those linter changes. :)

2024-03-11 13:58 UTC, steelhead31 approved these changes
LGTM

2024-03-11 15:25 UTC, sxa commented
Merging so that it's ready for the JDK22 dry run pipelines later this week.

2024-03-11 15:25 UTC, merged

2024-03-11 15:28 UTC, sxa commented
Rebuild of linux images happening under https://ci.adoptium.net/job/centos7_docker_image_updater/471