Doc: Update docker static patching policy
adoptium/infrastructure pull request #3161
Opened 2023-08-11 15:57 UTC by Haroon-Khel

- [ ] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

ref https://github.com/adoptium/infrastructure/issues/2962

Update to the dockerstatic docs now that https://github.com/adoptium/infrastructure/pull/3152 is merged

2023-08-11 16:54 UTC, sxa requested changes

2023-08-11 16:54 UTC, sxa commented on FAQ.md
> +At the moment we have the [updatepackages.sh](https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/scripts/updatepackages.sh) script
Can you update this to make it clear how the regular update is done (i.e. via AWX rather than a cron job)

2023-08-15 14:35 UTC, sxa requested changes
Suggest adding a link to the patching job too ([This one](https://awx2.adoptopenjdk.net/#/templates/job_template/34)?) or at least mentioning it by name.
Also please ensure that the initial commit has the `doc:` prefix on it

2023-09-01 11:44 UTC, sxa approved these changes

2023-09-04 02:02 UTC, karianna approved these changes

2023-09-04 02:02 UTC, merged