inventory: Correct the OS for dockerhost skytap machine
adoptium/infrastructure pull request #3163
Opened 2023-08-14 11:12 UTC by Haroon-Khel

- [ ] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

```
root@dockerhost-skytap-ubuntu2004-ppc64le-1:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
```
Incorrectly named 2204 when its OS is 2004

2023-08-14 11:21 UTC, sxa approved these changes

2023-08-14 11:22 UTC, sxa requested changes
Clicked too soon - can you add `inventory:` as a prefix on the commit message please?

2023-08-21 15:50 UTC, gdams approved these changes

2023-08-22 04:24 UTC, karianna approved these changes

2023-08-23 16:35 UTC, sxa approved these changes

2023-08-24 11:08 UTC, merged