UnixPB: Update Debian URLs
adoptium/infrastructure pull request #3174
Opened 2023-09-01 12:08 UTC by steelhead31

Fixes #3173 

Update URLs for GPG and repository to adoptium.

##### Checklist

- [X] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)

2023-09-01 12:09 UTC, steelhead31 commented
VPC check in progress: https://ci.adoptium.net/job/VagrantPlaybookCheck/1706/

2023-09-04 02:00 UTC, karianna approved these changes

2023-09-05 08:28 UTC, gdams reviewed
Two nits

2023-09-05 08:28 UTC, gdams commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml
>  - name: Add AdoptOpenJDK GPG key
```suggestion
- name: Add Eclipse Temurin GPG key
```

2023-09-05 08:28 UTC, gdams commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml
>  - name: Add the adoptopenjdk repository to apt for JDK8
```suggestion
- name: Add the Eclipse Temurin repository to apt for JDK8
```

2023-09-05 08:44 UTC, adamfarley approved these changes
LGTM - Does this mean the file folder will be renamed to Adoptium too?

2023-09-05 08:55 UTC, steelhead31 commented
> LGTM - Does this mean the file folder will be renamed to Adoptium too?

Not at this stage, this PR simply points the URL at their correct location, as the old ones no longer work, everything else should remain the same ( for now! )

2023-09-05 08:57 UTC, gdams requested changes
Just realised, you'll need to change https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Debian.yml#L71 too

2023-09-05 09:02 UTC, steelhead31 commented
> Just realised, you'll need to change https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Debian.yml#L71 too
> 
> Switch it to `temurin-8-jdk`

Good spot, done!

2023-09-05 09:03 UTC, gdams approved these changes

2023-09-05 10:05 UTC, merged