unixpb: Add Xcode11 installation tasks to Unix playbook
adoptium/infrastructure pull request #3197
Opened 2023-09-26 12:10 UTC by Haroon-Khel

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

ref https://github.com/adoptium/infrastructure/issues/2536

Xcode11.7 is required on m1 mac machines in order to cross compile x64 jdk8

Our usual method of installing xcode using `xcversion` is no longer supported https://github.com/xcpretty/xcode-install/blob/master/MIGRATION.md and is causing errors when I use it to install xcode11.7, see https://github.com/adoptium/infrastructure/issues/2536#issuecomment-1733623397

[xcodes](https://github.com/xcpretty/xcode-install/blob/master/MIGRATION.md) is another tool used to install different versions of xcode but I think it is dependent on Xcode13 which I believe requires macOS 11.3+ (our M1 machines are 11.0)

2023-09-26 12:26 UTC, sxa reviewed
We would ideally want to ensure that if the vendor_files is not available then this does not cause a playbook failure (other people using our playbooks may not have it available). We should have some way to trap this (May be telling people to use a skip-tags option for the role telling people to install it manually, or just warning and continuing. Or maybe we should abort if the adoptopenjdk tag is not skipped)

2023-09-27 10:22 UTC, sxa commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Xcode11/tasks/main.yml
> +# The Xcode11.7 package should be present in /Vendor_Files/mac/Xcode_11.7.xip on the controller node
Can we add something in here to indicate where the package comes from (i.e. "Log into developer.apple.com with an Apple developer ID to download this package" (I don't know if that URL is correct so please adjust accordingly ;-) ) to make it easy for others to use this role if desired.

2023-09-27 13:35 UTC, Haroon-Khel commented
The transfer process takes around 40mins. The binary is 7.6G. 

And this may be due to timeout reasons, but after the transfer is complete ansible hangs. It hung for about 30mins before I interrupted the execution. I'll test to see if AWX shows the same behaviour

2023-09-27 16:39 UTC, Haroon-Khel commented
Awx run https://awx2.adoptopenjdk.net/#/jobs/playbook/1910?job_search=page_size:20;order_by:-finished;not__launch_type:sync

2023-09-28 07:58 UTC, karianna requested changes

2023-09-28 07:58 UTC, karianna commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Xcode11/tasks/main.yml
> +# The Xcode11.7 package should be present in /Vendor_Files/mac/Xcode_11.7.xip on the controller node
complaints about trailing spaces

2023-09-28 12:33 UTC, Haroon-Khel commented
Tested this pr on test-macstadium-macos11-arm64-1. Works as expected

2023-09-28 12:37 UTC, Haroon-Khel commented
Running from AWX, the transfer takes the same time as running it from my machine, around 40mins. I dont think this is too bad as we are not seeing timeout errors

2023-09-30 02:53 UTC, karianna approved these changes

2023-10-02 16:20 UTC, Haroon-Khel commented
I've rolled out xcode11.7 onto the 4 arm64 mac machines

2023-10-02 16:55 UTC, sxa approved these changes

2023-10-02 16:55 UTC, sxa commented
> Running from AWX, the transfer takes the same time as running it from my machine, around 40mins. I dont think this is too bad as we are not seeing timeout errors

Yeah that's fine sine it's a one off and won't happen on subsequent runs of the playbook :-)

2023-11-16 22:00 UTC, gdams commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Xcode11/tasks/main.yml
> +    - name: Transfer Xcode11.7 over to remote machine
Replace with Azure blob storage

2023-11-16 22:11 UTC, gdams approved these changes

2023-11-16 22:22 UTC, gdams commented
I'm going to go ahead and push this as it's blocking my Orka review

2023-11-16 22:22 UTC, merged