doc: update FAQ with how to add new repository to AdoptOpenJDK dockerhub
adoptium/infrastructure pull request #3295
Opened 2023-12-13 13:18 UTC by Haroon-Khel

- [ ] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

ref https://github.com/adoptium/infrastructure/issues/2753#issuecomment-1853901010

2023-12-13 14:29 UTC, sxa approved these changes

2023-12-13 19:37 UTC, karianna approved these changes

2023-12-13 19:37 UTC, merged

2023-12-14 13:17 UTC, tellison requested changes
Typo

2023-12-14 13:17 UTC, tellison commented on FAQ.md
> +- Tim Ellison @telisson
@tellison

2023-12-14 13:33 UTC, Haroon-Khel commented on FAQ.md
> +- Tim Ellison @telisson
Not sure how I missed that