Vagrant: Improve VPC Performance For Windows Server 2022
adoptium/infrastructure pull request #3644
Opened 2024-07-02 08:39 UTC by steelhead31

Fixes #3553 

Due to poor performance of the Windows Server 2022  vagrant playbook check job, this PR makes a number of improvements to reduce the time taken to build, notably these are:

1) The addition of the "Use Adoptium Box" option, this has only been implemented (currently) for Windows 2022, and when selected will switch the VPC job from using the standard Vagrantfile.Win2022 file, to using the Vagrantfile.Win2022.Adopt file. This 2nd new vagrantfile uses an Adoptium specific vagrant box ( stored on the vagrant server but also imported to all the VPC hosts vagrant boxes ). This vagrant box, is a fully updated ( as of 25th June ) Windows Server 2022 install, so the windows update task in the playbook is much quicker.

2) The 2nd major change, is the selective install of MSVS versions based on the JDK version selected, ( this requires the selection of the fast mode option )

JDK8 will limit the playbook to only installing MSVS_2013
JDK11 will limit the playbook to only installing MSVS_2017
JDK17 will limit the playbook to only installing MSVS_2019
JDK21/JDK22 and JDK head will limit the playbook to only installing MSVS_2022

- [X] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [X] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)

2024-07-02 09:14 UTC, karianna requested changes
Changes look broadly good but suspect tabs vs spaces or some such...

2024-07-02 09:14 UTC, karianna commented on ansible/pbTestScripts/vagrantPlaybookCheck.sh
> +	--use-adopt | -ua							 Use the local Adoptium vagrantfile instead of the standard (.Adopt extension on Vagrantfile)
whitespace?

2024-07-02 09:14 UTC, karianna commented on ansible/pbTestScripts/vagrantPlaybookCheck.sh
> +  	ln -sf vagrant/Vagrantfile.$OS Vagrantfile
whitespace?  Same below?

2024-07-02 09:14 UTC, karianna commented on ansible/vagrant/Vagrantfile.Win2022.Adopt
> +
```suggestion
```

2024-07-02 12:28 UTC, steelhead31 commented on ansible/pbTestScripts/vagrantPlaybookCheck.sh
> +	--use-adopt | -ua							 Use the local Adoptium vagrantfile instead of the standard (.Adopt extension on Vagrantfile)
Fixed

2024-07-02 12:28 UTC, steelhead31 commented on ansible/pbTestScripts/vagrantPlaybookCheck.sh
> +  	ln -sf vagrant/Vagrantfile.$OS Vagrantfile
Fixed

2024-07-02 12:28 UTC, steelhead31 commented on ansible/vagrant/Vagrantfile.Win2022.Adopt
> +
Fixed

2024-07-03 00:53 UTC, karianna approved these changes

2024-07-03 00:54 UTC, karianna approved these changes

2024-07-03 00:54 UTC, karianna commented on ansible/pbTestScripts/vagrantPlaybookCheck.sh
> +	--use-adopt | -ua              Use the local Adoptium vagrantfile instead of the standard (.Adopt extension on Vagrantfile)
This one still seems indented wrong

2024-07-03 00:54 UTC, karianna commented on ansible/pbTestScripts/vagrantPlaybookCheck.sh
> +    ln -sf vagrant/Vagrantfile.$OS Vagrantfile
This one still seems indented wrong

2024-07-03 00:54 UTC, karianna commented on ansible/pbTestScripts/vagrantPlaybookCheck.sh
> +	    ln -sf ${scriptPath%/*}/../vagrant/Vagrantfile.$OS.Adopt Vagrantfile
This one still seems indented wrong

2024-07-03 11:24 UTC, gdams approved these changes

2024-07-03 11:54 UTC, sxa approved these changes

2024-07-03 12:56 UTC, merged