Vagrant: Update Vagrant Host Playbook & Introduce 2 new Azure vagrant hosts for VPC / QEMU
adoptium/infrastructure pull request #3704
Opened 2024-08-12 14:30 UTC by steelhead31

Commision 2 new azure based hosts for running VPC / QEMU

##### Checklist

- [X] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

2024-08-12 14:33 UTC, sxa reviewed
Given the amount of updates here I feel this may be a PR where I decide to approve it based on the fact it's been tested rather than because I've reviewed in detail ;-)

2024-08-12 14:42 UTC, steelhead31 commented
VPC test runs : [https://ci.adoptium.net/job/SFR-VPC-AZURE-POC/](https://ci.adoptium.net/job/SFR-VPC-AZURE-POC/)  
 

Qemu test runs : https://ci.adoptium.net/job/SFRY-QEMU-POC/

2024-09-02 09:27 UTC, Haroon-Khel approved these changes
Approving based on the tests

2024-09-02 13:51 UTC, sxa reviewed
A couple of initial comments:
- Can we add a description of the new python script perhaps with basic usage info as comments at the top?
- It looks like we're installing JDK17 on the machine - assuming this is just for the jenkins agent process can we bump to 21?

2024-09-02 14:59 UTC, steelhead31 commented on ansible/pbTestScripts/vagrantPlaybookCheck.sh
> +	  ansible-playbook $verbosity -i playbooks/AdoptOpenJDK_Unix_Playbook/hosts.unx -u vagrant -b --skip-tags adoptopenjdk,jenkins${skipFullSetup} playbooks/AdoptOpenJDK_Unix_Playbook/main.yml 2>&1 | te
Done.

2024-09-02 16:15 UTC, steelhead31 commented
> A couple of initial comments:
> 
> *   Can we add a description of the new python script perhaps with basic usage info as comments at the top?
> *   It looks like we're installing JDK17 on the machine - assuming this is just for the jenkins agent process can we bump to 21 and install via the API to ensure we get the latest version of 21?

I've removed the new python script, I rewrote this to run via vagrant rm, so its quicker and it retains its interactive output facility.  
  
I've bumped the JDK installation from JDK17 to JDK21, installed via the API.

2024-09-03 06:55 UTC, gdams requested changes

2024-09-03 06:55 UTC, gdams commented on ansible/pbTestScripts/vagrantPlaybookCheck.sh
> +	if [ "$OS" == "Solaris10" ]; then
It would probably be better to build an Args variable up rather than directly running the playbook in the if logic?

2024-09-03 07:49 UTC, steelhead31 commented
New test run in progress with changes following review comments... https://ci.adoptium.net/job/SFR-VPC-AZURE-POC/49/

2024-09-03 10:47 UTC, sxa requested changes
Ref:
```
- name: Set VirtualBox extension pack license agreement
```
I assume we've looked at it and there's nothing of concern in there before auto-accepting this?
```
echo "DEBUG - SF01"
```
These should be removed. I assume you already plan to do this but I just wanted to make sure it was still blocked until the change has been made, hence leaving my review as "Request changes" :-)
```
v.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
```
Bumping this from 50 to 80 makes me a little nervous as it could overwhelm machines that are running with multiple executors, potentially leading to timeouts in the runs. I'm willing to give it a shot if you think it'll be "safe" but we should keep an eye on it.

2024-09-03 11:14 UTC, steelhead31 commented
@sxa QPC runs are here: [https://ci.adoptium.net/job/SFRY-QEMU-POC/,](https://ci.adoptium.net/job/SFRY-QEMU-POC/,) they behave similar to the real ones :)

The debug is something Im working on now ( trying to rationalise the playbook execution statement, but its being problematic)

I've reverted the CPU cap, again its been left in from my local testing.. its fine with 50 on the remote host :)

2024-09-03 11:15 UTC, steelhead31 commented
@sxa I've removed the extpack license agreement, and uninstalled it. Thanks for the heads up

2024-09-03 11:23 UTC, steelhead31 commented
Reverting to draft, whilst I fix up the playbook execution

2024-09-03 14:20 UTC, steelhead31 commented
CPU cap at 50% isnt sufficient for the azure boxes, but 60% is, so I've bumped it to that, if needed, we can look to change this again, once the large vagrant host has been rebuilt.

2024-09-03 15:46 UTC, steelhead31 commented
I think I've addressed all the review comments, new test runs are here, [https://ci.adoptium.net/job/SFR-VPC-AZURE-POC/OS=Solaris10,label=vagrantX/55/console](https://ci.adoptium.net/job/SFR-VPC-AZURE-POC/OS=Solaris10,label=vagrantX/55/console) , [https://ci.adoptium.net/job/SFR-VPC-AZURE-POC/58/OS=CentOS8,label=vagrantX/console](https://ci.adoptium.net/job/SFR-VPC-AZURE-POC/58/OS=CentOS8,label=vagrantX/console) & https://ci.adoptium.net/job/SFR-VPC-AZURE-POC/OS=Win2022,label=vagrantX/59/console

2024-09-04 11:30 UTC, sxa approved these changes
Assuming it passes your tests I reckon I'm ok with this now :-)

2024-09-04 14:09 UTC, merged