UnixPB: Add Fedora 40 Support
adoptium/infrastructure pull request #3761
Opened 2024-10-02 08:38 UTC by steelhead31

Fixes #3599 

Correct Unix playbooks to allow execution on Fedora 40.

##### Checklist

- [X] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [X] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)

Fedora 40: VPC : https://ci.adoptium.net/job/VagrantPlaybookCheck/1974/

2024-10-03 09:31 UTC, karianna requested changes

2024-10-03 09:31 UTC, karianna commented on ansible/pbTestScripts/vmDestroy.sh
> +								"Fedora40" | "fedora40" | "F40" | "F40" )
whitespace seems out

2024-10-03 09:45 UTC, steelhead31 commented on ansible/pbTestScripts/vmDestroy.sh
> +								"Fedora40" | "fedora40" | "F40" | "F40" )
fixed, thanks!.

2024-10-03 19:39 UTC, karianna approved these changes

2024-10-04 10:12 UTC, sxa approved these changes
I'm ok with this, but noting:
- are there any implications on older Fedora versions of completely removing `libnss3.so` here - I think that was added for some of the security tests.
- Noting that in the `nasm` playbook we have a mix of syntax: `ansible_distribution == "Ubuntu" and ansible_distribution_major_version < "22")` vs `(ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int >= 24)`. I definitely have a recollection - possibly ansible version specific - that one is better than the other so maybe we should standardise. I have a feeling it was the `| int` version that was preferable but don't hold me to that :-)

2024-10-04 13:40 UTC, steelhead31 commented
> *   are there any implications on older Fedora versions of completely removing `libnss3.so` here - I think that was added for some of the security tests.

For the currently supported versions of Fedora ( 39 & 40 ) the libnss3 libraries are installed via nss-devel & nss-util packages, so removing it has no impact on the currently supported versions.  
  
The vagrant playbook checks run the SSL tests as part of the TEST\_JDK flag, so this would highlight any issues for the Fedora 40 run.  
 

> *   Noting that in the `nasm` playbook we have a mix of syntax: `ansible_distribution == "Ubuntu" and ansible_distribution_major_version < "22")` vs `(ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int >= 24`

I've standardised this to be consistent for all the major version checks. I believe the int comparison is a more reliable comparison for numeric values, particularly as using \<= with string operations is a bit inconsistent. the string operations are fine for a simple ==.

2024-10-04 14:12 UTC, merged

2024-10-04 15:17 UTC, sxa commented
@steelhead31 I guess this supercedes https://github.com/adoptium/infrastructure/pull/3663?

2024-10-04 15:20 UTC, steelhead31 commented
> @steelhead31 I guess this supercedes #3663?

Yup, I hadnt seen the earlier one.